import os

SECRET_KEY = os.urandom(24)
SQLALCHEMY_DATABASE_URI = 'sqlite:///site.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
UPLOAD_FOLDER = 'static/portfolio'
RECAPTCHA_SECRET_KEY = '6Lc7ZWgrAAAAALKvR4nIXoBKCdzYNjgKgEiH2feq'