
SECRET_KEY = 'your-secret-key'
SQLALCHEMY_DATABASE_URI = 'sqlite:///site.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
UPLOAD_FOLDER = 'static/portfolio'
RECAPTCHA_SECRET_KEY = '6LfnbWgrAAAAAOZUjf91CPAjBoWoFVDQGxxR0QZ1'
